### ISSUE TITLE
add "Videos" to title?

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-perspective-videos#32]
Current title of main page is:
> Web Accessibility Perspectives: Explore the Impact and Benefits for Everyone

Shortname in nav is:
> Perspectives Videos

Do we want to add "Videos" to the main title? 
> Web Accessibility Perspectives Videos: Explore the Impact and Benefits for Everyone

and a line break? 
> Web Accessibility Perspectives Videos:
> Explore the Impact and Benefits for Everyone

**Comment by bakkenb** [comment]
**Adding the word:** Does this improve SEO? I am guessing it may. My opinion is it couldn't hurt to add the word, and it could actually help in multiple ways. 

**Line Break:** At 100% browser zoom I think the line is going to naturally break there anyway so I don't see a problem with adding the line break in so it stays when zooming in or out. Will it have any impact on mobile?

**Comment by slhenry** [comment]
+1s from [EOWG telecon 29 Jan 2021](https://www.w3.org/2021/01/29-eo-minutes#t03)
