### ISSUE TITLE
add resource name under sub-page titles?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-perspective-videos#33]
For sub-pages of multi-page resources, we now have set up to include the main resource name under the H1. For example, [captions page in media resource](https://www.w3.org/WAI/media/av/captions/) has:
> **Captions/Subtitles**
> _in Making Audio and Video Media Accessible_

Do we want to add that for the Perspectives Video sub-pages? For example, [Video Captions](https://www.w3.org/WAI/perspective-videos/captions/)
> **Video Captions**
> _in Web Accessibility Perspectives Videos_

(related issue https://github.com/w3c/wai-perspective-videos/issues/32 )

**Comment by bakkenb** [comment]
Is this a change that is also being considered site wide for all multi-page resources? I would assume it is, so I think best to be consistent and include. 

I do like how the additional "main resource text" is an actual link to the overview/start page of the resource. Another way to get back to the beginning without using the left-nav.

**Comment by slhenry** [comment]
> Is this a change that is also being considered site wide for all multi-page resources?

Yes, we're doing it wherever it improves usability and accessibility.

**Comment by slhenry** [comment]
+1s from [EOWG telecon 29 Jan 2021](https://www.w3.org/2021/01/29-eo-minutes#t03)

**Comment by slhenry** [comment]
reopened 'cause it's not implemented yet - awaiting new code...

**Comment by remibetin** [comment]
@shawna-slh I've implemented it in #61: I needed the same option to group the French translations of this resource in "All Translations"

**Comment by remibetin** [comment]
Implemented: see https://www.w3.org/WAI/perspective-videos/contrast/ for example :)
