### ISSUE TITLE
[Voice] voice vs speech recognition

### ISSUE THREAD

**Issue by yatil** [w3c/wai-perspective-videos#5]
_From @nitedog on March 13, 2017 23:5_

From Gary Morin: [speech recognition may be more technically correct](https://lists.w3.org/Archives/Public/wai-eo-editors/2017Mar/0000.html)

_Copied from original issue: w3c/wai-showcase-examples#317_

**Comment by slhenry** [comment]
Proposed edits to Speech Recognition page:
* [preview](https://deploy-preview-41--wai-perspective-videos.netlify.app/perspective-videos/voice/)
* [diff](https://github.com/w3c/wai-perspective-videos/pull/41/files)
